version: '3'

services:
  db:
    image: postgres:14
    container_name: store-db
    restart: always
    tty: true
    ports:
      - '5434:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: store-db

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    container_name: store-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  shop-db-data:
